### ISSUE TITLE
Failure to import python 3.5.4 on Windows

### ISSUE THREAD

**Issue by jdclarke5** [ClearcodeHQ/pytest-mongo#227]
### What action do you want to perform

Import and use package using Python 3.5.4 running on Windows.

### What are the results

```sh
>>> from pytest_mongo import factories                                                                                                                                                           Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Jackson Clarke\AppData\Local\Programs\Python\Python35\lib\site-packages\pytest_mongo\factories.py", line 25, in <module>
    from mirakuru import TCPExecutor
  File "C:\Users\Jackson Clarke\AppData\Local\Programs\Python\Python35\lib\site-packages\mirakuru\__init__.py", line 24, in <module>
    from mirakuru.output import OutputExecutor
  File "C:\Users\Jackson Clarke\AppData\Local\Programs\Python\Python35\lib\site-packages\mirakuru\output.py", line 30, in <module>
    class OutputExecutor(SimpleExecutor):
  File "C:\Users\Jackson Clarke\AppData\Local\Programs\Python\Python35\lib\site-packages\mirakuru\output.py", line 107, in OutputExecutor
    def _wait_for_output(self, *polls: Tuple[select.poll, IO[Any]]) -> bool:
AttributeError: module 'select' has no attribute 'poll'
```

### What are the expected results

Successful import. Not sure if Python 3.5 is the problem (is it supported?), or Windows. May be similar to [github.com/ClearcodeHQ/mirakuru/pull/333](https://github.com/ClearcodeHQ/mirakuru/pull/333).

**Comment by fizyk** [comment]
@jdclarke5 that issue is strictly related with mirakuru, however it's not tested on windows, and I do not have that much time at the moment to spend on proper Windows support there. However I welcome all help here

References: 

https://github.com/ClearcodeHQ/mirakuru/issues/392

**Comment by fizyk** [comment]
actually I'm marking this as duplicate for this: https://github.com/ClearcodeHQ/mirakuru/issues/336.

@jdclarke5 please subscribe to both related stories, and I'll welcome any contribution in that direction.
